### ISSUE TITLE
Board running hot

### ISSUE THREAD

**Issue by AdamKGoddard** [AdamKGoddard/XiaomiIR_ESPHome#1]
Whilst running code, board and ESP32 are hot.
Whilst in bootloader, both are cool.
Suspect a GPIO used for a hard coded setting with the original needs to be configured to be in a correct state?

**Comment by AdamKGoddard** [comment]
Inverted sends incorrect IR codes but leaves the board cool. Seems to be a idle state issue. Tested and confirmed with just switching IR LED on GPIO26 on and off. GPIO26 default state needs to be set to high when not sending.

**Comment by ekorsanov01** [comment]
After sending any IR code board starts to heat up. ((((
