### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by Oleg-Sob** [AdamKGoddard/XiaomiIR_ESPHome#9]
Gives an error message: 
Error! Failed to extract upstream toolchainconfigurations:
Bad package version `1.22.0-97-gc752ad5-5.2.0`
You can disable this feature via the `board_build.arduino.upstream_packages = no` setting in your `platformio.ini` file.

Tell me how to fix it?

**Comment by 19leva89** [comment]
The same pronblem!
Error! Failed to extract upstream toolchainconfigurations:
Bad package version `1.22.0-80-g6c4433a-5.2.0`
You can disable this feature via the `board_build.arduino.upstream_packages = no` setting in your `platformio.ini` file.

ESPHome 2023.8.2
Home Assistant 2023.8.3

**Comment by AdamKGoddard** [comment]
Try the latest commit, I completely refactored and upgraded to esp-idf

**Comment by AdamKGoddard** [comment]
you'll need to update the pre script and remote_transmitter_esp32.cpp as well in the esphome directory

**Comment by 19leva89** [comment]
Successfully compiled program. Thanks bro!

**Comment by Oleg-Sob** [comment]
Thanks, compiled. IR Remote did not try to flash.

**Comment by AdamKGoddard** [comment]
Gonna mark this one as fixed, haven't had any issues compiling since the framework change. Thanks for the feebback and testing.

**Comment by 19leva89** [comment]
Yes, everything works without problems, thanks! But now I want to switch to the Arduino framework and for this I ordered a dual-core ESP32-D0WD-V3 chip

**Comment by AdamKGoddard** [comment]
For dual core, should just be able to run esphome as normal and choose a board that uses the ESP32-D0WD-V3. This project was only to support the single core processor used in the Xiaomi IR controller and others.

**Comment by 19leva89** [comment]
I have an idea to use a board and case from Xiaomi IR controller and replace the processor on the board on ESP32-D0WD-V3
